plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.165'
    id "me.modmuss50.mod-publish-plugin" version '0.7.4'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

//minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')
//minecraft.accessTransformers.entry public net.minecraft.client.Minecraft textureManager # textureManager


runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }

    gameTestServer {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }


configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    /* YACL */
    maven { url 'https://maven.isxander.dev/releases/' }
    maven { url 'https://thedarkcolour.github.io/KotlinForForge/' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://maven.quiltmc.org/repository/release/' }

    maven { url 'https://maven.terraformersmc.com/releases/' } // EMI
    maven { url 'https://maven.shedaniel.me/' } // REI
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    implementation "thedarkcolour:kotlinforforge-neoforge:${project.kotlinforforge_version}"

    compileOnly "dev.isxander:yet-another-config-lib:${project.yacl_version}-neoforge"
    jarJar "dev.isxander:yet-another-config-lib:${project.yacl_version}-neoforge"
    runtimeOnly "dev.isxander:yet-another-config-lib:${project.yacl_version}-neoforge"

    compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${project.rei_version}"
    compileOnly "dev.emi:emi-neoforge:${emi_version}:api"

    switch(project.active_recipe_viewer) {
        case "rei":
            runtimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${project.rei_version}"
            break
        case "emi":
            runtimeOnly  "dev.emi:emi-neoforge:${project.emi_version}"
            break
    }

}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

ext.getChangeLog = { ->
    return "- First Neoforge release"
}

publishMods {
    changelog = project.getChangeLog()
    type = STABLE

    def optionsCurseforge = curseforgeOptions {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = "576449"
        projectSlug = "coxinha-utilities"
        minecraftVersions.add("${project.minecraft_version}")
    }

    def optionsModrinth = modrinthOptions {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "NXqpbY3F"
        minecraftVersions.add("${project.minecraft_version}")
    }


    curseforge("curseforgeForge") {
        from optionsCurseforge
        modLoaders.add("neoforge")
        file = jar.archiveFile
        displayName = "${rootProject.mod_version} (NeoForge)"
        version = "${rootProject.mod_version}-neoforge"

        optional {
            slug = "emi"
        }
        optional {
            slug = "kibe"
        }

        announcementTitle = "Download from CurseForge"
    }


    modrinth("modrinthForge") {
        from optionsModrinth
        modLoaders.add("neoforge")
        file = jar.archiveFile
        displayName = "${rootProject.mod_version} (NeoForge)"
        version = "${rootProject.mod_version}-neoforge"

        optional {
            slug = "emi"
        }
        optional {
            slug = "kibe"
        }

        announcementTitle = "Download from Modrinth"
    }

    discord {
        webhookUrl = providers.environmentVariable("CAFETERIA_MOD_RELEASE_WEBHOOK")
        username = "Coxinha Utilities (Neoforge)"
        avatarUrl = "https://cdn.modrinth.com/data/NXqpbY3F/icon.png"

        content = changelog.map { "# Coxinha Utilities (Neoforge) " + (project.mod_version as String) + " has been released \n" + it}
    }
}