# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false
# Neoforge Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
neo_version=21.1.68
neo_version_range=[21.1.1,)
loader_version_range=[4,)
neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28
# Dependencies
yacl_version=3.5.0+1.21
kotlinforforge_version=5.5.0
rei_version=16.0.777
emi_version=1.1.13+1.21.1
# Mod Properties
mod_id=coxinhautilities
mod_name=Coxinha Utilities
mod_license=Apache-2.0
mod_version=1.5+1.21
mod_group_id=me.luligabi.coxinhautilities
mod_authors=Luligabi
mod_description=A utility mod featuring stuff missing from Kibe Utilities.
# Testing
active_recipe_viewer=rei
# Publishing
curseforge_id=576449
modrinth_id=NXqpbY3F