modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/coxinha-utilities"
#logoFile="examplemod.png" #optional
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
    config="${mod_id}.mixins.json"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId = "yet_another_config_lib_v3"
    type = "required"
    versionRange = "1.0" # any version
    ordering = "NONE"
    side = "CLIENT"
[[dependencies.${mod_id}]]
    modId = "kibe"
    type = "optional"
    reason="integration"
    versionRange = "1.0" # any version
    ordering = "NONE"
    side = "BOTH"